### ISSUE TITLE
Seeing an issue on the images 101 example

### ISSUE THREAD

**Issue by adaschevici** [qdrant/examples#36]
👋 this is more of a question, not sure if I am doing something wrong and have not managed to debug the problem fully so bear with me.

I am trying to work through the Image data tutorial and I am getting a strange error:

it seems to be breaking down when I try to process the cell
```python
inputs = processor(images=image, return_tensor="pt").to(mps_device)
```

```shell
Cell In[9], line 2
      1 type(image)
----> 2 inputs = processor(images=image, return_tensor="pt").to(mps_device)
      3 # inputs["pixel_values"].shape, inputs
...
    227 for k, v in self.items():
    228     # check if v is a floating point
    229     __import__("pdb").set_trace()
--> 230     if torch.is_floating_point(v):
    231         # cast and send to device
    232         new_data[k] = v.to(*args, **kwargs)
    233     elif device is not None:

TypeError: is_floating_point(): argument 'input' (position 1) must be Tensor, not list
```

I am trying it with Python 3.11.8 also trying to apply on the MPS device rather than cuda. I have tried using CPU instead but seeing the same. I have also tried using a different model but getting similar issue.

```toml
[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
jupyterlab = "^4.1.2"
faker = "^23.3.0"
qdrant-client = "^1.7.3"
transformers = "^4.38.2"
datasets = "^2.18.0"
torch = "^2.2.1"
sentence-transformers = "^2.5.1"
ipywidgets = "^8.1.2"
jupyterlab-widgets = "^3.0.10"
torchvision = "^0.17.1"
```

Can anyone point me where to look for a solution?
